const names = [
  'Aaran',
  'Aaren',
  'Aarez',
  'Aarman',
  'Aaron',
  'Aaron-James',
  'Aarron',
  'Aaryan',
  'Aaryn',
  'Aayan',
  'Aazaan',
  'Abaan',
  'Abbas',
  'Abdallah',
  'Abdalroof',
  'Abdihakim',
  'Abdirahman',
  'Abdisalam',
  'Abdul',
  'Abdul-Aziz',
  'Abdulbasir',
  'Abdulkadir',
  'Abdulkarem',
  'Smith',
  'Jones',
  'Coollastname',
  'enter_name_here',
];

const emails = [
  'aaron@example.com',
  'aaron.james@example.com',
  'aarron@example.com',
  'aaryan@example.com',
  'aaryn@example.com',
  'aayan@example.com',
  'aazaan@example.com',
  'abaan@example.com',
  'abbas@example.com',
  'abdallah@example.com',
  'abdalroof@example.com',
  'abdihakim@example.com',
  'abdirahman@example.com',
  'abdisalam@example.com',
  'abdul@example.com',
  'abdul.aziz@example.com',
  'abdulbasir@example.com',
  'abdulkadir@example.com',
  'abdulkarem@example.com',
  'smith@example.com',
];

const thoughts = [
  "Here's a cool thought...",
  "I love programming!",
  "JavaScript is awesome!",
  "MongoDB is a NoSQL database.",
  "Express makes server-side development easy.",
  "React is a powerful front-end library.",
  "Node.js allows JavaScript to run on the server.",
  "Mongoose is an ODM for MongoDB.",
  "APIs are essential for modern web development.",
  "RESTful APIs follow a architecture.",
  "GraphQL is an alternative to REST.",
  "JSON is a lightweight data format.",
  "AJAX allows asynchronous web requests.",
  "Promises simplify asynchronous code.",
  "Async/await makes asynchronous code look synchronous.",
  "Callbacks are a way to handle asynchronous operations.",
  "Event-driven programming is powerful.",
  "Functional programming has many benefits.",
  "Object-oriented programming is widely used.",
  "Software development is a rewarding career.",
];

const users = names.slice(0, 20).map((name, index) => ({
  username: name,
  email: emails[index],
  thoughts: [],
  friends: [],
}));

const exampleThoughts = thoughts.slice(0, 20).map((thought, index) => ({
  thoughtText: thought,
  username: users[index % users.length].username,
  reactions: [],
}));

module.exports = { users, exampleThoughts };